# Generated by Django 3.2.20 on 2023-08-30 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='post',
            name='kilometers_ran',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
