# Generated by Django 3.2.20 on 2023-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1_blog', '0002_auto_20230830_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
