# Generated by Django 3.2.20 on 2023-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1_blog', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
